version: '3'
services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=products_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password

  web:
    build: .
    ports:
      - 8080:8080